packages:
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.32.0
  '@types/node': ^22.14.1
  '@typescript-eslint/eslint-plugin': ^8.44.0
  '@typescript-eslint/parser': ^8.44.0
  '@typescript-eslint/utils': ^8.44.0
  eslint: ^9.32.0
  eslint-config-expo: ^10.0.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-n: ^17.21.3
  eslint-plugin-prettier: ^5.5.3
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  prettier: ^3.6.2
  tsconfigs: ^5.0.0
  typescript: 5.8.3
  typescript-eslint: ^8.44.0

onlyBuiltDependencies:
  - unrs-resolver
